### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by pgoddardmiles** [vampd/vampd#16]
Suggestions:

On OS, enable color highlighting of command line stuff.

Add git shortcuts by default, so "git co" (checkout), "git ci" etc.  Meaning, make it possible to set git config stuff for vagrant user. As well as the current branch on command line. All that goodness we have within Miles.

**Comment by timodwhit** [comment]
Usings the vampd/vampd-developer cookbook, both of these are now possible. 

Add the cookbook to your berkshelf, add the recipes to your runlist, set the flags and you should be good, let me know if you need help with that.
