### ISSUE TITLE
Assets folder Missing

### ISSUE THREAD

**Issue by beardedbrew** [vampd/vampd#29]
I might be missing something there but in the instructions you mention sharing to an /assets folder, but in my folder after performing a git clone there is no assets folder.

Once I make one everything is fine. Might be a little confusing for the average user.

**Comment by timodwhit** [comment]
@beardedbrew: Thank you so much for the suggestion. I went ahead and added a note under the instructions. Feel free to submit a issue or PR if the instructions still need clarification.
