### ISSUE TITLE
Our 12.04 base box is out of date and too small

### ISSUE THREAD

**Issue by chrisolof** [vampd/vampd#32]
As an interim step on the way to an Ubuntu 14.04 box I think we should use an up-to-date 12.04 base box.  Also, why not use an official Ubuntu base box?  What's our tie-in with this puppetlabs box?  We don't even use puppet...

Also - this box's hard drive maxes out at around 9GB - which is proving too small for some of my projects - and I know other users have been hitting this out-of-space issue too.

Once #30 makes it in, we could easily swap out this outdated puppetlabs box for an always-up-to-date (until 12.04 is no longer supported), official box straight from Ubuntu's servers (with a flexible HD that can grow up to 32GB as needed):

https://cloud-images.ubuntu.com/vagrant/precise/current/precise-server-cloudimg-amd64-vagrant-disk1.box

I'll be testing this new box out today in some development tasks to ensure it's compatible.

**Comment by timodwhit** [comment]
Does the box take up 32gb of space or just allow for it?

**Comment by chrisolof** [comment]
It allows for growth up to 32GB, but does not start anywhere near that big.  The actual size is whatever the OS occupies + any packages, dbs, software, etc. you add into it.  Same goes for our current base box, except that it caps the HD's max size at 8 or 9GB.

**Comment by chrisolof** [comment]
Happy to report that after a day of heavy coding atop it, everything seems just fine on this official Ubuntu base box.  Anyone else want to try it out?  I can PR this new base box once #30 makes it in.

**Comment by timodwhit** [comment]
So #30 was merged in. Feel free to submit your PR
